name: Guard Placeholder Tokens

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  placeholder-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for placeholder tokens
        run: |
          # List of tokens that should be replaced before merge
          TOKENS="<REPO_URL>|<your-org>|YOUR-ORG"
          echo "Scanning repository for placeholder tokens: $TOKENS"
          # Grep returns non-zero exit code if no matches are found with -q, we invert that logic
          if grep -RIE "$TOKENS" --exclude-dir=.git --exclude-dir=.venv .; then
            echo "\n❌ Placeholder tokens detected. Please replace them before merging."
            exit 1
          else
            echo "✅ No placeholder tokens found."
          fi 